### ISSUE TITLE
Missed field in Sqlite Database header and wrong offset for Application ID.

### ISSUE THREAD

**Issue by Neopallium** [FreeMasen/WiredForge.com#49]
I am enjoying your "SQLite Parser" blog posts.

I noticed one issue in part 3.

The "Application ID" is at offset 68 not 64: https://github.com/FreeMasen/WiredForge.com/blob/c0528ce3506630b6de0c103e7d09fcbf9b4bb348/content/blog/sqlite_parser_pt_3.md?plain=1#L1061

The "incremental-vacuum mod" field is at offset 64.

From the Sqlite file format table:
```
60	4	The "user version" as read and set by the [user_version pragma](https://sqlite.org/pragma.html#pragma_user_version).
64	4	True (non-zero) for incremental-vacuum mode. False (zero) otherwise.
68	4	The "Application ID" set by [PRAGMA application_id](https://sqlite.org/pragma.html#pragma_application_id).
72	20	Reserved for expansion. Must be zero.
```

**Comment by FreeMasen** [comment]
Thank you for this correction, I will get it updated tonight!

**Comment by FreeMasen** [comment]
I just pushed an update that should show up online shortly. I think I might need to review the prose and code to include the value at 64

**Comment by Neopallium** [comment]
```rust
    let application_id = crate::try_parse_u32(&bytes[68..72], "application id")?;
    validate_reserved_zeros(&bytes[68..92]).map_err(|e| eprintln!("{}", e)).ok();
```
The `validate_reserved_zeros` range overlaps.  It should be `72..92` (20 bytes).

**Comment by FreeMasen** [comment]
Thank you again for reporting this. I finally got around to updating the prose of part 3 and the code in part 4 with this new value. I have also added [a correction post on the blog](https://freemasen.com/blog/sqlite-parser-pt-3-a/) with a brief summary and a link to the new section of part 3
