### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by Michael-F-Bryan** [FreeMasen/WiredForge.com#7]
I've been playing around with using WASM as a plugin mechanism over the last couple days, and even started putting together [a kind of extended example/walkthrough thing][repo] ([rendered]).

I saw your blog post(s) mentioned in the latest *This Week in Rust* and was wondering if you would be interested in collaborating? I'm keen to act as a rubber ducky you can bounce ideas off, or even help in a proofreading/co-author capacity.

[repo]: https://github.com/Michael-F-Bryan/create-a-botnet
[rendered]: https://michael-f-bryan.github.io/create-a-botnet/book/index.html

**Comment by FreeMasen** [comment]
Hey, thanks for reaching out. I am sorry I didn't see this, I am not sure how exactly but my GitHub notifications seem to be broken in some way. 

I haven't really been working in the web-assembly space over the last few years unfortunately but Build a BotNet seems like a really fun tutorial!
